import { createHash } from "node:crypto";
import { and, eq } from "drizzle-orm";
import { db } from "@workspace/db";
import { aiceoAgentRunsTable, aiceoAgentVerificationsTable, aiceoCollaborationIssuesTable, aiceoContinuityProjectsTable, aiceoContinuityStateTable, aiceoControlStateTable, aiceoExecutionContractsTable } from "@workspace/db/schema";

const digest=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
const forbidden=(v:unknown)=>/password|secret|token|credential|api[_ -]?key/i.test(JSON.stringify(v));
const DENIES=["production","trading","databento","alert","shell","workflow","network","database"];
export class AiceoAgentExecutionProtocol {
 constructor(private readonly database:any=db,private readonly existingTransaction=false){}
 private transact<T>(work:(tx:any)=>Promise<T>):Promise<T>{return this.existingTransaction?work(this.database):this.database.transaction(work)}
 async issue(input:any,actorId:string){return this.transact(async tx=>{
  const p=(await tx.select().from(aiceoContinuityProjectsTable).limit(1))[0],s=(await tx.select().from(aiceoContinuityStateTable).limit(1).for("update"))[0];
  if(!p||!s||input.continuityRevision!==s.revision)throw new Error("不能：stale persistent state");
  if(forbidden(input))throw new Error("不能：秘密或凭据不得进入 Agent context");
  if(input.ownerAttentionBudget?.maxOwnerInterruptions>1||input.ownerAttentionBudget?.mergeHumanActions!==true||input.ownerAttentionBudget?.noScreenshotWhenAutoVerifiable!==true)throw new Error("不能：Owner Attention Budget must minimize and merge Owner actions");
  const old=(await tx.select().from(aiceoExecutionContractsTable).where(eq(aiceoExecutionContractsTable.idempotencyKey,input.idempotencyKey)).limit(1))[0];if(old)return old;
  const body={...input,projectId:p.id,brainActorId:actorId,contextHash:digest({revision:s.revision,state:s.currentState,rules:s.decisionRuleRegistry}),deniedCapabilities:[...new Set([...input.deniedCapabilities,...DENIES])],authorityBoundaries:{ownerSovereignty:true,ownerProtectionTriad:true,authority:"delegated_technical_authority",productionAuthority:false},contractVersion:"BRAIN-AGENT-001",productionAuthority:false};
  return (await tx.insert(aiceoExecutionContractsTable).values({...body,contractHash:digest(body)}).returning())[0];
 })}
 async start(contractId:string,input:any){return this.transact(async tx=>{
  const control=(await tx.select().from(aiceoControlStateTable).limit(1).for("update"))[0],c=(await tx.select().from(aiceoExecutionContractsTable).where(eq(aiceoExecutionContractsTable.id,contractId)).for("update"))[0],s=(await tx.select().from(aiceoContinuityStateTable).limit(1))[0];
  if(!control||control.killSwitch||!control.queueActive||control.circuitState==="OPEN")throw new Error("不能：control gate closed");
  if(!c||!s||c.continuityRevision!==s.revision||input.contextHash!==c.contextHash)throw new Error("不能：stale contract/context");
  if(input.delegationDepth>c.maxDelegationDepth||input.inheritedAuthority!=="delegated_technical_authority")throw new Error("不能：delegation authority expansion");
  const old=(await tx.select().from(aiceoAgentRunsTable).where(and(eq(aiceoAgentRunsTable.contractId,contractId),eq(aiceoAgentRunsTable.idempotencyKey,input.idempotencyKey))).limit(1))[0];if(old)return old;
  if(c.status!=="ISSUED")throw new Error("不能：terminal or active contract replay");
  await tx.update(aiceoExecutionContractsTable).set({status:"RUNNING"}).where(eq(aiceoExecutionContractsTable.id,c.id));
  return (await tx.insert(aiceoAgentRunsTable).values({...input,contractId,state:"RUNNING",checkpoint:{node:c.resumeNode,partialSuccess:false},observedScope:[],deadlineAt:new Date(Date.now()+Number(c.executionPolicy.timeoutMs))}).returning())[0];
 })}
 async checkpoint(runId:string,input:any){return this.transact(async tx=>{const r=(await tx.select().from(aiceoAgentRunsTable).where(eq(aiceoAgentRunsTable.id,runId)).for("update"))[0],c=r&&(await tx.select().from(aiceoExecutionContractsTable).where(eq(aiceoExecutionContractsTable.id,r.contractId)).limit(1))[0];if(!r||!c||r.state!=="RUNNING")throw new Error("不能：active run missing");if(forbidden(input)||input.usedCalls>Number(c.executionPolicy.maxCalls)||input.usedCostMicrousd>Number(c.executionPolicy.maxCostMicrousd)||input.retryCount>Number(c.executionPolicy.maxRetries))throw new Error("不能：checkpoint secret, retry, call, or cost budget violation");if(["FAILED","OWNER_GATE"].includes(input.state)&&!input.blocker)throw new Error("不能：真实 capability blocker required");await tx.update(aiceoAgentRunsTable).set({...input,updatedAt:new Date(),heartbeatAt:new Date()}).where(eq(aiceoAgentRunsTable.id,runId));return{state:input.state,checkpoint:input.checkpoint,escalateTo:input.state==="OWNER_GATE"?"owner":"brain",productionAuthority:false}})}
 async resume(runId:string,contextHash:string){return this.transact(async tx=>{const control=(await tx.select().from(aiceoControlStateTable).limit(1).for("update"))[0],r=(await tx.select().from(aiceoAgentRunsTable).where(eq(aiceoAgentRunsTable.id,runId)).for("update"))[0],s=(await tx.select().from(aiceoContinuityStateTable).limit(1))[0],c=r&&(await tx.select().from(aiceoExecutionContractsTable).where(eq(aiceoExecutionContractsTable.id,r.contractId)).limit(1))[0];if(!control||control.killSwitch||!control.queueActive||control.circuitState==="OPEN")throw new Error("不能：control gate closed");if(!r||!c||!s||r.state!=="PAUSED"||contextHash!==c.contextHash||c.continuityRevision!==s.revision)throw new Error("不能：stale or non-resumable checkpoint");await tx.update(aiceoAgentRunsTable).set({state:"RUNNING",heartbeatAt:new Date(),updatedAt:new Date()}).where(eq(aiceoAgentRunsTable.id,runId));return{state:"RUNNING",checkpoint:r.checkpoint,productionAuthority:false}})}
 async submit(runId:string,input:any){return this.transact(async tx=>{const r=(await tx.select().from(aiceoAgentRunsTable).where(eq(aiceoAgentRunsTable.id,runId)).for("update"))[0],c=r&&(await tx.select().from(aiceoExecutionContractsTable).where(eq(aiceoExecutionContractsTable.id,r.contractId)).limit(1))[0];if(!r||!c)throw new Error("不能：run missing");if(new Date()>r.deadlineAt||input.usedCalls>Number(c.executionPolicy.maxCalls)||input.usedCostMicrousd>Number(c.executionPolicy.maxCostMicrousd))throw new Error("不能：timeout, call, or cost budget exceeded");if(forbidden(input)||input.observedScope.some((x:string)=>!c.allowedCapabilities.includes(x))||!input.evidence.length)throw new Error("不能：scope drift, secret, or missing evidence");await tx.update(aiceoAgentRunsTable).set({...input,state:"AWAITING_VERIFICATION",updatedAt:new Date()}).where(eq(aiceoAgentRunsTable.id,runId));await tx.update(aiceoExecutionContractsTable).set({status:"AWAITING_VERIFICATION"}).where(eq(aiceoExecutionContractsTable.id,c.id));return{state:"AWAITING_VERIFICATION",verified:false,productionAuthority:false}})}
 async verify(runId:string,input:any,validator:string){return this.transact(async tx=>{const r=(await tx.select().from(aiceoAgentRunsTable).where(eq(aiceoAgentRunsTable.id,runId)).for("update"))[0];if(!r||r.agentActorId===validator||r.state!=="AWAITING_VERIFICATION")throw new Error("不能：independent verification required");const required=["authority","scope","understanding","noDuplicate","noOwnerInterruption","evidence"],compliant=required.every(k=>input.compliance?.[k]===true),passed=input.passed&&compliant;await tx.insert(aiceoAgentVerificationsTable).values({runId,validatorActorId:validator,passed,compliance:input.compliance,evidence:input.evidence,resultHash:digest(r.result),finalStatus:passed?"VERIFIED":"REJECTED"});await tx.update(aiceoAgentRunsTable).set({state:passed?"VERIFIED":"REJECTED"}).where(eq(aiceoAgentRunsTable.id,runId));await tx.update(aiceoExecutionContractsTable).set({status:passed?"VERIFIED":"REJECTED"}).where(eq(aiceoExecutionContractsTable.id,r.contractId));if(!passed)await tx.insert(aiceoCollaborationIssuesTable).values({projectId:(await tx.select().from(aiceoContinuityProjectsTable).limit(1))[0].id,category:"execution_friction",summary:"Agent behavioral compliance failure",evidence:input.evidence,context:{runId,compliance:input.compliance},status:"CAPTURED",createdBy:validator});return{finalStatus:passed?"VERIFIED":"REJECTED",productionAuthority:false}})}
}
export const aiceoAgentExecutionProtocol=new AiceoAgentExecutionProtocol();